version: '2'
services:
  puppet:
    build:
      context: .
      dockerfile: Dockerfile.puppet
    container_name: puppet
    hostname: puppet
    domainname: ene.local
    image: eneuhauss/project_puppet5_puppetmaster:1.1
    volumes:
      - $PWD/../../code:/etc/puppetlabs/code
    entrypoint:
      - /opt/puppetlabs/bin/puppet
      - master
      - --no-daemonize
      - --debug
      # - /opt/puppetlabs/bin/puppetserver
      # - foreground
      # - --debug

  node1:
    build:
      context: .
      dockerfile: Dockerfile.node1
    container_name: node1
    hostname: node1
    domainname: ene.local
    image: eneuhauss/project_puppet5_node1:1.1
    depends_on:
      - puppet
    links:
      - puppet
    entrypoint: dockerize -wait tcp://puppet:8140 -timeout 60s /opt/puppetlabs/bin/puppet agent --no-daemonize --debug
