# Dockerfile based on the latest debian 8 image
FROM debian:8
MAINTAINER eneuhauss@gmx.de

RUN apt-get update && \
    apt-get -y install \
    puppetmaster \
    ruby-msgpack

#ENV PATH "$PATH:/opt/puppetlabs/bin"

ADD config/3x/puppet/etc/puppet/puppet.conf /etc/puppet/puppet.conf

RUN mkdir -p \
    /etc/puppet/files \
    /etc/puppet/templates
