# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'config'

boxes = [
    {
      :name => "control.example.local",
      :ip =>  "172.28.128.110",
    },
    {
      :name => "node1.example.local",
      :ip =>  "172.28.128.111",
    },
    {
      :name => "node2.example.local",
      :ip =>  "172.28.128.112",
    },
    {
      :name => "node3.example.local",
      :ip =>  "172.28.128.113",
    }
]

Vagrant.configure("2") do |create|
  boxes.each do |box|
    create.vm.define box[:name] do |config|
      config.ssh.insert_key = false
      config.vm.provider :virtualbox do |vb|
        vb.check_guest_additions = false
        vb.name = box[:name]
        vb.customize ["modifyvm", :id, "--vram", "8"] # ubuntu defaults to 256 MB which is a waste of precious RAM
      end
      config.vm.box = "generic/centos8"
      config.vm.network :private_network, ip: box[:ip]
    end # config.vm
  end # boxes.each.loop
end # Vagrant
