apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc-registry
  namespace: registry
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-cephfs
