apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc-default
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
