---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephblock-pvc-registry
  namespace: registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
