---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  collections:
    - community.kubernetes
  vars:
    namespace: monitoring

  tasks:
    - name: get list of pods in "{{ namespace }}"
      k8s_info:
        namespace: "{{ namespace }}"
        kind: pod
        label_selectors:
          - app = grafana
      register: pod_list

    - name: progress when conditions met
      when: pod_list['resources'] | list | length > 0
      block:
        - name: print pods name
          debug:
            msg: "pod: {{ pod_list | json_query('resources[*].metadata.name') }}"

        - set_fact:
            pod_name: "{{ pod_list | json_query('resources[0].metadata.name') }}"

        - name: exec in grafana container
          k8s_exec:
            namespace: "{{ namespace }}"
            pod: "{{ pod_name }}"
            command: grafana-cli admin reset-admin-password admin
          register: pod_cmd
          failed_when: not pod_cmd.stdout.find('Admin password changed successfully') !=-1

        - name: print pod_pwd variable 
          debug:
            var: pod_cmd
          when: pod_cmd is succeeded
