apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-webapp-ingress
  namespace: default
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: webapp.fritz.box
    http:
      paths:
      - path: /color
        pathType: Prefix
        backend:
          service:
            name: webapp-color
            port:
              number: 80
              # this did not work. No image at http://webapp.fritz.box/mysql
              # /static/img/success.jpg 404
              #      - path: /mysql
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp-mysql
            port:
              number: 80
