apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-webapp-ingress
  namespace: default
spec:
  rules:
  - host: webapp.fritz.box
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: webapp-mysql
            port:
              number: 80
      - path: /color
        pathType: ImplementationSpecific
        backend:
          service:
            name: webapp-color
            port:
              number: 80
