FROM registry.fritz.box/my/arm64v8/latex_minion:2020-basic
MAINTAINER eneuhauss@gmx.de

ENV PATH /usr/local/texlive/2020/bin/aarch64-linux:$PATH

# Install required packages first
RUN yum update -y && 	\
    yum install -y --setopt=tsflags=nodocs \
        dnf-plugins-core \
        git \
        make \
        wget && \
    yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && \
    yum config-manager --set-enabled powertools && \
    yum update -y && \
    yum install -y --setopt=tsflags=nodocs perl-Tk perl-Digest-MD5 && \
    yum -y clean all
# Install TeXLive basic with MinionPro Support
RUN mkdir -p /usr/local/src &&  \
    wget -q -P /usr/local/src   \
        http://ftp.gwdg.de/pub/ctan/systems/texlive/tlnet/install-tl-unx.tar.gz \
        https://raw.githubusercontent.com/erolneuhauss/studies/master/docker/latex_minion/job_appl_sample.tex \
        https://raw.githubusercontent.com/erolneuhauss/studies/master/docker/latex_minion/octocat.png \
        https://raw.githubusercontent.com/erolneuhauss/studies/master/docker/latex_minion/texlive2020-arm64-full.profile && \
    tar xzf /usr/local/src/install-tl-unx.tar.gz -C /usr/local/bin &&   \
    perl /usr/local/bin/install-tl-*/install-tl \
        -profile /usr/local/src/texlive2020-arm64-full.profile
RUN mktexlsr /usr/local/texlive/texmf-local && \
    tex -version && \
    latex -version && \
    cd /usr/local/src && \
    latex $(find /usr/local -name sample2e.tex) && \
    pdflatex $(find /usr/local -name sample2e.tex) && \
    pdflatex /usr/local/src/job_appl_sample.tex && \
    pdflatex /usr/local/src/job_appl_sample.tex && \
    rm -f /usr/local/src/* && \
    yum remove -y \
        git \
        perl-Digest-MD5 \
        perl-Tk && \
    yum -y clean all && \
    rm -rf /var/cache/yum
RUN mkdir /texcode
WORKDIR  /texcode
