version: '2'
services:
  web:
    container_name: upload_php_nginx
    environment:
      - PHP_UPLOAD_MAX_FILESIZE=300
      - PHP_POST_MAX_SIZE=300
    image: richarvey/nginx-php-fpm
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./upload:/var/www/html/upload
      - ./upload:/var/www/html
      - ./additional.ini:/usr/local/etc/php/conf.d/additional.ini
      - ./default_site_nginx.conf:/etc/nginx/sites-available/default.conf  
    ports:
      - "80:80"
