filetype off
set cursorline
set encoding=utf8
set expandtab
set hlsearch
set incsearch
set number
set shiftwidth=2
set showcmd
set softtabstop=2
set tabstop=2
execute pathogen#infect()
execute pathogen#helptags()
filetype plugin indent on
syntax on
let g:airline_theme='powerlineish'
set guifont=Droid\ Sans\ Mono\ for\ Powerline\ Nerd\ Font\ Complete\ Windows\ Compatible:h14
"let g:airline_powerline_fonts=1
set laststatus=2
set background=dark
set t_Co=256
colorscheme solarized
