---
- hosts: all
  become: true
  gather_facts: true
  #  vars:
  #    ansible_become_pass: "yvDwwNRxie"
  tasks:
    - copy:
        src: files/hwlist.txt
        dest: /tmp/hwlist.txt

    - replace:
        path: /tmp/hwlist.txt
        regexp: "{{ item.FROM }}"
        replace: "{{ item.TO }}"
      loop:
        - FROM: "FQDN.*"
          TO: "FQDN={{ ansible_fqdn }}"
        - FROM: "BIOS.*"
          TO: "BIOS_VERSION={{ ansible_bios_version }}"
        - FROM: "TOTAL.*"
          TO: "TOTAL_RAM={{ ansible_memtotal_mb }}"
        - FROM: "XVDA_SIZE.*"
          TO: "XVDA_SIZE={{ ansible_devices['xvda']['size'] }}"
        - FROM: "XVDB_SIZE.*"
          TO: "XVDG_SIZE={% if ansible_devices['xvdg'] is defined %}{{ ansible_devices['xvdg']['size'] }}{% else %}NONE{% endif %}"

    - shell: cat /tmp/hwlist.txt
      register: report
      changed_when: false
    - debug:
        var: report.stdout_lines

