boxes = [
    {
        :name => "swarm-master-00",
        :ip   => "172.28.128.20",
    },
    {
        :name => "swarm-node-01",
        :ip   => "172.28.128.21",
    },
    {
        :name => "swarm-node-02",
        :ip   => "172.28.128.22",
    },
]


Vagrant.configure("2") do |my|
  boxes.each do |box|
    my.vm.define box[:name] do |config|
      config.vm.box = "ubuntu/focal64"
      config.vm.hostname = box[:name]
      config.vm.network "private_network", ip: box[:ip]
    end # config.vm
  end # boxes.each.loop

  my.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end # config.vm.provision
end # Vagrant
