---
# tasks file for sample-mysql
- name: create partition
  parted:
    device: /dev/sdb
    number: 1
    flags: [ lvm ]
    part_end: 800MiB
    state: present

- name: create vg
  lvg:
    vg: vg_database
    pvs: /dev/sdb1

- name: create lvol
  lvol:
    vg: vg_database
    lv: lv_mysql
    size: 512m

- name: mkfs.xfs
  filesystem:
    dev: /dev/vg_database/lv_mysql
    fstype: xfs

- name: mount lvol
  mount:
    src: /dev/vg_database/lv_mysql
    path: /mnt/mysql_backups
    state: mounted
    fstype: xfs

- name: install mysql and python
  yum:
    name:
      - mysql-server
      - python2-PyMySQL
      - python3-PyMySQL
    state: installed

- name: firewall
  firewalld:
    port: 3306/tcp
    zone: public
    permanent: true
    immediate: true
    state: enabled

- service:
    name: mysqld
    state: started
    enabled: true

- name: mysql user
  mysql_user:
    name: root
    password: "{{ database_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: mysql credentials for root
  template:
    src: creds.j2
    dest: /root/.my.cnf
    owner: root
    group: root

- service:
    name: mysqld
    state: restarted

- template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
