kind: PersistentVolume
apiVersion: v1
metadata:
  name: puppet
  labels:
  namespace: myproject
    type: local
    app: puppet
    deploymentconfig: puppet
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
