---
version: '3.3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
#  webapp:
#    build:
#      context: ./app
#      dockerfile: Dockerfile
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD="R00tP4ssw0rd"
      - MYSQL_DATABASE="app_name"
      - MYSQL_USER="db_user"
      - MYSQL_PASSWORD="4pp_n4meP4sswrd0!"
  webapp:
    image: php:7.0-apache
    volumes:
      - app_data:/var/www/html
      - app_logs:/var/logs/apache2
    links:
      - db
    ports:
      - 80:80
volumes:
  app_data:
  app_logs:
  db_data:

