#!~/.local/bin/ansible-playbook
---
# rm -f nginx-webcontent.yml && k -n nginx create configmap nginx-webcontent --from-file=usr-share-nginx-html $do > nginx-webcontent.yml && k apply -f nginx-webcontent.yml && k -n nginx rollout restart deployment nginx && k -n nginx get pods -o wide --watch

- name: deploy kubernetes nginx
  hosts: localhost
  connection: local
  serial: 1
  gather_facts: false
  become: false
  collections:
    - community.kubernetes
  tasks:
    - name: remove current configmap file
      file:
        path: nginx-configmap-multi.yml
        state: absent

    - name: delete configmap
      k8s:
        state: absent
        api_version: v1
        kind: ConfigMap
        namespace: nginx
        name: nginx-configmap-multi

    - name: create new configmap file
      shell: kubectl --namespace=nginx create configmap nginx-configmap-multi --from-file=etc-nginx --dry-run=client --output=yaml > nginx-configmap-multi.yml

    - name: read definition file
      k8s:
        state: present
        src: nginx-configmap-multi.yml

    - name: deploy nginx
      k8s:
        state: present
        src: nginx-deploy.yml

    - name: restart deployment
      shell: kubectl --namespace=nginx rollout restart deployment nginx
