apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp-mysql-static
  name: webapp-mysql-static-service
  namespace: webapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp-mysql-static
  type: ClusterIP
