apiVersion: v1
kind: Service
metadata:
  namespace: webapp
  name: webapp-mysql-static-service
  labels:
    app: webapp-mysql-static
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: webapp-mysql-static
  type: ClusterIP
