---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: delete containers
      loop: "{{ groups['ansible'] }}"
      lxd_container:
        name: "{{ item }}"
        state: absent
        url: "{{ lxd_server_url }}"
        trust_password: "lxd_server_trust_password_url }}"
