kind: Service
apiVersion: v1
metadata:
  namespace: webapp
  name: webapp-mysql-web-service
  labels:
    app: webapp-mysql-web
spec:
  selector:
    app: webapp-mysql-web
  ports:
  - name: http
    port: 8080
    targetPort: http
