apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
  namespace: webapp
  name: webapp-mysql-web-traefik-ingress
spec:
  rules:
  - host: webapp.fritz.box
    http:
      paths:
      - path: /mysql
        pathType: Prefix
        backend:
          serviceName: webapp-mysql-web-service
          servicePort: http
