---
- name: configure daemon.json
  hosts: all
  gather_facts: false
  tasks:
    - name: copy daemon.json to /etc/docker
      copy:
        src: docker-daemon.json
        dest: /etc/docker/daemon.json
