#!~/.local/bin/ansible-playbook
---
- name: downscale with method instead of using "all"
  hosts: localhost
  connection: local
  serial: 1
  gather_facts: false
  become: false
  collections:
    - community.kubernetes
  vars:
    namespace:
      - deployment: kanboard
        name: kanboard
      - deployment: db
        name: kanboard
      - deployment: docker-registry
        name: registry
      - deployment: helm-controller
        name: flux-system
      - deployment: kustomize-controller
        name: flux-system
      - deployment: notification-controller
        name: flux-system
      - deployment: source-controller
        name: flux-system
      - deployment: prometheus-operator
        name: monitoring
      - deployment: prometheus-adapter
        name: monitoring
      - deployment: mysqld-exporter-prometheus-mysql-exporter
        name: monitoring
      - deployment: kube-state-metrics
        name: monitoring
      - deployment: grafana
        name: monitoring
      - deployment: dashboard-metrics-scraper
        name: kubernetes-dashboard
      - deployment: kubernetes-dashboard
        name: kubernetes-dashboard
      - deployment: metrics-server
        name: kube-system
      - deployment: rook-ceph-operator
        name: rook-ceph
      - deployment: rook-ceph-tools
        name: rook-ceph
      - deployment: rook-ceph-mgr-a
        name: rook-ceph
      - deployment: rook-ceph-mon-b
        name: rook-ceph
      - deployment: rook-ceph-mon-c
        name: rook-ceph
      - deployment: rook-ceph-mon-e
        name: rook-ceph
      - deployment: rook-ceph-mon-f
        name: rook-ceph
      - deployment: rook-ceph-mon-g
        name: rook-ceph
      - deployment: rook-ceph-mds-myfs-a
        name: rook-ceph
      - deployment: rook-ceph-mds-myfs-b
        name: rook-ceph
      - deployment: rook-ceph-osd-0
        name: rook-ceph
      - deployment: rook-ceph-osd-1
        name: rook-ceph
      - deployment: rook-ceph-osd-2
        name: rook-ceph
      - deployment: rook-ceph-osd-3
        name: rook-ceph
      - deployment: rook-ceph-osd-4
        name: rook-ceph
      - deployment: rook-ceph-osd-5
        name: rook-ceph
      - deployment: rook-ceph-osd-6
        name: rook-ceph
      - deployment: rook-ceph-osd-7
        name: rook-ceph
      - deployment: rook-ceph-osd-8
        name: rook-ceph
      - deployment: rook-ceph-osd-9
        name: rook-ceph
  tasks:
    - name: suspend flux-system
      command: >
        flux suspend kustomization flux-system

    - name: take care of kanboard
      block:
      - name: scale down kanboard deployment
        k8s_scale:
          api_version: v1
          kind: Deployment
          name: kanboard
          namespace: kanboard
          replicas: 0
          wait_timeout: 60

      - name: produce mysql backup
        command: >
          kubectl --namespace kanboard --stdin --tty exec deploy/db --
          /bin/bash -c 'mysqldump --user="$MYSQL_USER" --password="$MYSQL_PASSWORD" kanboard > /tmp/kanboard.sql'

      - name: get pod name
        k8s_info:
          namespace: kanboard
          kind: pod
          label_selectors:
            - app = db
        register: pod_list

      - set_fact:
          pod_name: "{{ pod_list | json_query('resources[0].metadata.name') }}"

      - name: copy file from pod to localhost
        command: >
          kubectl cp kanboard/{{ pod_name }}:/tmp/kanboard.sql ../backup/kanboard.sql

      - name: produce date
        shell: 'date +"%F"'
        register: today

      - name: add a git commmit message
        command: >
          git -C ~/git/private/raspberry-pi/raspberry-pi-dramble/kanboard/backup
          commit --message "kanboard db-backup of {{ today.stdout }}" kanboard.sql

      - name: git push
        command: >
          git -C ~/git/private/raspberry-pi/raspberry-pi-dramble/kanboard/backup push

      - name: archive old file
        archive:
          path: ../backup/kanboard.sql
          dest: ../backup/{{ today.stdout }}-kanboard.sql.gz
          format: gz
          force_archive: true
      ignore_errors: true

    - name: scale down deployments
      command: >
        kubectl
        --namespace "{{ item.name }}"
        scale deployment "{{ item.deployment }}"
        --replicas 0
        --timeout 30s
      loop: "{{ namespace }}"
      ignore_errors: true

    - name: look for running pods
      command: >
        kubectl
        --namespace "{{ item.name }}"
        get deployment "{{ item.deployment }}"
        -o custom-columns=REPLICAS:.status.availableReplicas
      register: availableReplicas
      loop: "{{ namespace }}"
      ignore_errors: true

    - name:
      debug:
        msg: "{{ availableReplicas | json_query('results[*].stdout_lines') | to_nice_json }}"

- name: drain nodes
  hosts: localhost
  connection: local
  serial: 5
  gather_facts: false
  become: false
  collections:
    - community.kubernetes

  tasks:
    - name: drain nodes
      tags:
        - drain
      command: >
        kubectl
        drain
        --ignore-daemonsets
        --delete-emptydir-data
        --force
        "{{ item }}"
      loop:
        - k8s-worker05.fritz.box
        - k8s-worker04.fritz.box
        - k8s-worker03.fritz.box
        - k8s-worker02.fritz.box
        - k8s-worker01.fritz.box
        - k8s-master02.fritz.box
