#!~/.local/bin/ansible-playbook
---
- name: downscale with method instead of using "all"
  hosts: localhost
  connection: local
  serial: 1
  gather_facts: false
  become: false
  collections:
    - community.kubernetes
  vars:
    namespace:
      - name: kanboard
        deployment: kanboard
      - name: kanboard
        deployment: db
      - name: webapp
        deployment: webapp-color
      - name: webapp
        deployment: webapp-mysql-db
      - name: webapp
        deployment: webapp-mysql-static
      - name: webapp
        deployment: webapp-mysql-web
      - name: webapp
        deployment: webapp-wear
      - name: registry
        deployment: docker-registry
      - name: drupal
        deployment: drupal
      - name: drupal
        deployment: mysql
      - name: default
        deployment: nfs-client-provisioner
      - name: default
        deployment: nginx
      - name: monitoring
        deployment: grafana
      - name: monitoring
        deployment: prometheus-operator
      - name: monitoring
        deployment: prometheus-adapter
      - name: monitoring
        deployment: kube-state-metrics
      - name: kube-system
        deployment: metrics-server
      - name: rook-ceph
        deployment: rook-ceph-operator
      - name: rook-ceph
        deployment: csi-cephfsplugin-provisioner
      - name: rook-ceph
        deployment: csi-rbdplugin-provisioner
      - name: rook-ceph
        deployment: rook-ceph-crashcollector-k8s-worker01.fritz.box
      - name: rook-ceph
        deployment: rook-ceph-crashcollector-k8s-worker02.fritz.box
      - name: rook-ceph
        deployment: rook-ceph-crashcollector-k8s-worker03.fritz.box
      - name: rook-ceph
        deployment: rook-ceph-mds-myfs-a
      - name: rook-ceph
        deployment: rook-ceph-mds-myfs-b
      - name: rook-ceph
        deployment: rook-ceph-mgr-a
      - name: rook-ceph
        deployment: rook-ceph-mon-d
      - name: rook-ceph
        deployment: rook-ceph-mon-b
      - name: rook-ceph
        deployment: rook-ceph-mon-c
      - name: rook-ceph
        deployment: rook-ceph-osd-0
      - name: rook-ceph
        deployment: rook-ceph-osd-1
      - name: rook-ceph
        deployment: rook-ceph-osd-2
      - name: rook-ceph
        deployment: rook-ceph-osd-3
      - name: rook-ceph
        deployment: rook-ceph-osd-4
      - name: rook-ceph
        deployment: rook-ceph-osd-5
      - name: rook-ceph
        deployment: rook-ceph-tools
  tasks:
    - import_playbook: mysqldump-kanboard-db.yml

    - name: scale down deployments
      command: >
        kubectl
        --namespace "{{ item.name }}"
        scale deployment "{{ item.deployment }}"
        --replicas 0
        --timeout 30s
      loop: "{{ namespace }}"
      ignore_errors: true

    - name: look for running pods
      command: >
        kubectl
        --namespace "{{ item.name }}"
        get deployment "{{ item.deployment }}"
        -o custom-columns=REPLICAS:.status.availableReplicas
      register: availableReplicas
      loop: "{{ namespace }}"
      ignore_errors: true

    - name:
      debug:
        msg: "{{ availableReplicas | json_query('results[*].stdout_lines') | to_nice_json }}"

    - name: drain nodes
      command: >
        kubectl
        drain
        --ignore-daemonsets
        --delete-emptydir-data
        --force
        "{{ item }}"
      loop:
        - k8s-worker03.fritz.box
        - k8s-worker02.fritz.box
        - k8s-worker01.fritz.box
