#!~/.local/bin/ansible-playbook
---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  collections:
    - community.kubernetes
  vars:
    namespace:
      - name: rook-ceph
        deployment: csi-cephfsplugin-provisioner
      - name: rook-ceph
        deployment: csi-rbdplugin-provisioner
      - name: rook-ceph
        deployment: rook-ceph-crashcollector-k8s-master01.fritz.box
      - name: rook-ceph
        deployment: rook-ceph-crashcollector-k8s-worker01.fritz.box
      - name: rook-ceph
        deployment: rook-ceph-crashcollector-k8s-worker02.fritz.box
      - name: rook-ceph
        deployment: rook-ceph-crashcollector-k8s-worker03.fritz.box
      - name: rook-ceph
        deployment: rook-ceph-mds-myfs-a
      - name: rook-ceph
        deployment: rook-ceph-mds-myfs-b
      - name: rook-ceph
        deployment: rook-ceph-mgr-a
      - name: rook-ceph
        deployment: rook-ceph-mon-d
      - name: rook-ceph
        deployment: rook-ceph-mon-b
      - name: rook-ceph
        deployment: rook-ceph-mon-c
      - name: rook-ceph
        deployment: rook-ceph-osd-0
      - name: rook-ceph
        deployment: rook-ceph-osd-1
      - name: rook-ceph
        deployment: rook-ceph-osd-2
      - name: rook-ceph
        deployment: rook-ceph-osd-3
      - name: rook-ceph
        deployment: rook-ceph-osd-4
      - name: rook-ceph
        deployment: rook-ceph-osd-5
      - name: rook-ceph
        deployment: rook-ceph-osd-6
      - name: rook-ceph
        deployment: rook-ceph-osd-7
      - name: rook-ceph
        deployment: rook-ceph-operator
      - name: rook-ceph
        deployment: rook-ceph-tools
      - name: kube-system
        deployment: metrics-server
      - name: monitoring
        deployment: kube-state-metrics
      - name: monitoring
        deployment: prometheus-adapter
      - name: monitoring
        deployment: prometheus-operator
      - name: monitoring
        deployment: grafana
      - name: default
        deployment: nfs-client-provisioner
#      - name: drupal
#        deployment: mysql
#      - name: drupal
#        deployment: drupal
      - name: registry
        deployment: docker-registry
      - name: kanboard
        deployment: db
      - name: kanboard
        deployment: kanboard

  tasks:
    - name: uncordon nodes
      command: >
        kubectl
        uncordon
        "{{ item }}"
      loop:
        - k8s-worker01.fritz.box
        - k8s-worker02.fritz.box
        - k8s-worker03.fritz.box

    - name: scale up deployments
      command: >
        kubectl
        --namespace "{{ item.name }}"
        scale deployment "{{ item.deployment }}"
        --replicas 1
      loop: "{{ namespace }}"

    - name: look for running pods
      command: >
        kubectl
        --namespace "{{ item.name }}"
        get deployment "{{ item.deployment }}"
        -o custom-columns=REPLICAS:.status.availableReplicas
      register: availableReplicas
      loop: "{{ namespace }}"

    - name:
      debug:
        msg: "{{ availableReplicas | json_query('results[*].stdout_lines') | to_nice_json }}"

