#!~/.local/bin/ansible-playbook
---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  collections:
    - community.kubernetes
  vars:
    namespace:
      - deployment: rook-ceph-operator
        name: rook-ceph
      - deployment: rook-ceph-mgr-a
        name: rook-ceph
      - deployment: rook-ceph-mon-b
        name: rook-ceph
      - deployment: rook-ceph-mon-c
        name: rook-ceph
      - deployment: rook-ceph-mon-d
        name: rook-ceph
      - deployment: rook-ceph-mon-e
        name: rook-ceph
      - deployment: rook-ceph-mon-f
        name: rook-ceph
      - deployment: rook-ceph-mds-myfs-a
        name: rook-ceph
      - deployment: rook-ceph-mds-myfs-b
        name: rook-ceph
      - deployment: rook-ceph-osd-0
        name: rook-ceph
      - deployment: rook-ceph-osd-1
        name: rook-ceph
      - deployment: rook-ceph-osd-2
        name: rook-ceph
      - deployment: rook-ceph-osd-3
        name: rook-ceph
      - deployment: rook-ceph-osd-4
        name: rook-ceph
      - deployment: rook-ceph-osd-5
        name: rook-ceph
      - deployment: rook-ceph-osd-6
        name: rook-ceph
      - deployment: rook-ceph-osd-7
        name: rook-ceph
      - deployment: rook-ceph-osd-8
        name: rook-ceph
      - deployment: rook-ceph-osd-9
        name: rook-ceph
      - deployment: rook-ceph-crashcollector-k8s-worker05.fritz.box
        name: rook-ceph
      - deployment: rook-ceph-crashcollector-k8s-worker04.fritz.box
        name: rook-ceph
      - deployment: rook-ceph-crashcollector-k8s-worker03.fritz.box
        name: rook-ceph
      - deployment: rook-ceph-crashcollector-k8s-worker02.fritz.box
        name: rook-ceph
      - deployment: rook-ceph-crashcollector-k8s-worker01.fritz.box
        name: rook-ceph
      - deployment: rook-ceph-tools
        name: rook-ceph
  tasks:
  tasks:
    - name: uncordon nodes
      command: >
        kubectl
        uncordon
        "{{ item }}"
      loop:
        - k8s-master02.fritz.box
        - k8s-worker01.fritz.box
        - k8s-worker02.fritz.box
        - k8s-worker03.fritz.box
        - k8s-worker04.fritz.box

    - name: scale up ceph deployments
      command: >
        kubectl
        --namespace "{{ item.name }}"
        scale deployment "{{ item.deployment }}"
        --replicas 1
      loop: "{{ namespace }}"

    - name: look for running pods
      command: >
        kubectl
        --namespace "{{ item.name }}"
        get deployment "{{ item.deployment }}"
        -o custom-columns=REPLICAS:.status.availableReplicas
      register: availableReplicas
      loop: "{{ namespace }}"

    - name:
      debug:
        msg: "{{ availableReplicas | json_query('results[*].stdout_lines') | to_nice_json }}"

    - name: get ceph cluster health
      tags: ceph
      command: >
        kubectl get
        --namespace rook-ceph
        cephcluster rook-ceph
      register: Health
      until: Health.stdout.find('HEALTH_OK') !=-1
      retries: 30
      delay: 60

    - name: Health message
      tags: ceph
      debug:
        msg: "{{ Health }}"

- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - ceph_dependend
  collections:
    - community.kubernetes
  vars:
    namespace:
      - deployment: helm-controller
        name: flux-system
      - deployment: kustomize-controller
        name: flux-system
      - deployment: notification-controller
        name: flux-system
      - deployment: source-controller
        name: flux-system
      - deployment: prometheus-operator
        name: monitoring
      - deployment: prometheus-adapter
        name: monitoring
      - deployment: mysqld-exporter-prometheus-mysql-exporter
        name: monitoring
      - deployment: kube-state-metrics
        name: monitoring
      - deployment: grafana
        name: monitoring
      - deployment: dashboard-metrics-scraper
        name: kubernetes-dashboard
      - deployment: kubernetes-dashboard
        name: kubernetes-dashboard
      - deployment: dev-the-deployment
        name: default
      - deployment: prod-the-deployment
        name: default
      - deployment: docker-registry
        name: registry
      - deployment: db
        name: kanboard
      - deployment: kanboard
        name: kanboard
  tasks:
    - name: scale up deployments depending on ceph
      command: >
        kubectl
        --namespace "{{ item.name }}"
        scale deployment "{{ item.deployment }}"
        --replicas 1
      loop: "{{ namespace }}"

    - name: look for running pods
      command: >
        kubectl
        --namespace "{{ item.name }}"
        get deployment "{{ item.deployment }}"
        -o custom-columns=REPLICAS:.status.availableReplicas
      register: availableReplicas
      loop: "{{ namespace }}"

    - name: resume flux-system
      command: >
        flux resume kustomization flux-system

    - name:
      debug:
        msg: "{{ availableReplicas | json_query('results[*].stdout_lines') | to_nice_json }}"
