#!~/.local/bin/ansible-playbook
---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  collections:
    - community.kubernetes
  vars:
    namespace:
      - name: registry
        deployment: docker-registry
      - name: kanboard
        deployment: db
      - name: kanboard
        deployment: kanboard
  tasks:
    - name: uncordon nodes
      command: >
        kubectl
        uncordon
        "{{ item }}"
      loop:
        - k8s-master02.fritz.box
        - k8s-worker01.fritz.box
        - k8s-worker02.fritz.box
        - k8s-worker03.fritz.box
        - k8s-worker04.fritz.box

    - name: scale up deployments
      command: >
        kubectl
        --namespace "{{ item.name }}"
        scale deployment "{{ item.deployment }}"
        --replicas 1
      loop: "{{ namespace }}"

    - name: look for running pods
      command: >
        kubectl
        --namespace "{{ item.name }}"
        get deployment "{{ item.deployment }}"
        -o custom-columns=REPLICAS:.status.availableReplicas
      register: availableReplicas
      loop: "{{ namespace }}"

    - name:
      debug:
        msg: "{{ availableReplicas | json_query('results[*].stdout_lines') | to_nice_json }}"
