version: '2'
services:
  puppet:
    build:
      context: .
      dockerfile: Dockerfile.puppet
    container_name: puppet
    hostname: puppet
    image: eneuhauss/mypuppetmaster:v5.0
    entrypoint:
      - /opt/puppetlabs/bin/puppet
      - master
      - --debug
      - --no-daemonize

  node1:
    build:
      context: .
      dockerfile: Dockerfile.node1
    container_name: node1
    hostname: node1
    image: eneuhauss/mynode1:v5.0
    depends_on:
      - puppet
    links:
      - puppet
    entrypoint: dockerize -wait tcp://puppet:8140 /opt/puppetlabs/bin/puppet agent --no-daemonize --debug
