# Dockerfile based on the latest debian 8 image
FROM debian:8.8
MAINTAINER eneuhauss@gmx.de

RUN apt-get update && \
  apt-get -y upgrade &&  \
  apt-get -y install \
    vim \
    wget && \
  wget https://apt.puppetlabs.com/puppet5-release-jessie.deb && \
  dpkg -i puppet5-release-jessie.deb

RUN apt-get update && \
    apt-get -y install \
    puppet-agent

ENV PATH "$PATH:/opt/puppetlabs/bin"

RUN /opt/puppetlabs/bin/puppet agent --enable
