apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: frontend
  name: nginx-rs
  namespace: ene
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx-po
          image: nginx
          ports:
          - containerPort: 80

