apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: wordpress
  namespace: ene
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: wordpress
          image: wordpress
          ports:
          - containerPort: 80
          env:
            - name : WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_USER
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              value: password
            - name : WORDPRESS_DB_NAME
              value: wordpress
