---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoshow-cephfs-config-pvc
  namespace: photoshow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoshow-cephfs-pictures-pvc
  namespace: photoshow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoshow-cephfs-thumbs-pvc
  namespace: photoshow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
