# Dockerfile based on the latest debian 8 image
FROM debian:latest
MAINTAINER eneuhauss@gmx.de

RUN apt-get update && \
  apt-get -y upgrade &&  \
  apt-get -y install vim puppetmaster && \
  mkdir /etc/puppet/files && \
  mkdir /etc/puppet/templates && \
  mkdir -p /etc/puppet/environments/production/manifests && \
  mkdir /etc/puppet/environments/production/modules
