# Dockerfile based on the latest debian 8 image
FROM debian:latest
MAINTAINER eneuhauss@gmx.de

RUN apt-get update && \
  apt-get -y upgrade &&  \
  apt-get -y install \
    vim \
    puppetmaster \
    ruby-msgpack && \
  mkdir -p \
    /etc/puppet/files \
    /etc/puppet/templates \
    /etc/puppet/environments/production/manifests \
    /etc/puppet/environments/production/modules
