# Dockerfile based on the latest debian 8 image
FROM debian:latest
MAINTAINER eneuhauss@gmx.de

RUN apt-get update && \
  apt-get -y upgrade &&  \
  apt-get -y install vim puppet

ADD puppet/puppet.conf /etc/puppet/puppet.conf

RUN /usr/bin/puppet agent --enable

ENTRYPOINT  [ "/usr/bin/puppet", "agent", "--no-daemonize", "--verbose" ]
