version: '2'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - puppetmaster
    container_name: client
    hostname: client
    image: eneuhauss/myclient:v0.1
    links:
      - puppetmaster
    networks:
      mynetwork:
        aliases:
          - client
    volumes:
      - /Users/eneuhauss/enron_mail_20150507_10000_files:/dataset_10000_files
      - /Users/eneuhauss/enron_mail_20150507_5000_files:/dataset_5000_files

  puppetmaster:
    build:
      context: .
      dockerfile: Dockerfile.puppetmaster
    container_name: puppetmaster
    hostname: puppetmaster
    image: eneuhauss/mypuppetmaster:v0.1
    networks:
      mynetwork:
        aliases:
          - puppetmaster

networks:
  mynetwork:
    driver: bridge
