# Dockerfile based on the latest debian 8 image
FROM debian:latest
MAINTAINER eneuhauss@gmx.de

RUN apt-get update && \
  apt-get -y upgrade &&  \
  apt-get -y install puppetmaster 

ADD puppetmaster/puppetmaster.conf /etc/puppet/puppet.conf
#
#EXPOSE 8140
#
#ENTRYPOINT  [ "/usr/bin/puppet", "master", "--no-daemonize", "--verbose" ]
