version: '3'
services:
  web:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs/cert.crt:/etc/nginx/cert.crt
      - ./certs/cert.key:/etc/nginx/cert.key
    ports:
      - 80:80
      - 443:443
    command: [nginx-debug, '-g', 'daemon off;']

