#!/bin/sh
### BEGIN INIT INFO
# Provides:          windows7
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts/stops virtual machine ms_windows7
# Description:       starts/stops kvm based virtual machine ms_windows7
# coin-a-v-186.co-in.local has address 192.168.20.66
#
### END INIT INFO
# Author: Erol Neuhauß

# Aktionen
case "$1" in
    start)
#      /usr/local/bin/attach_public_bridge.sh
      sleep 5
      /usr/local/bin/start_ms_windows7.sh &
        ;;
    stop)
        ps -C qemu-system-x86_64
        WINDOWS7RUNNING=$?
        if [ $WINDOWS7RUNNING -eq 0 ]
        then
          echo Windows7 is running. Shutting it down
          echo system_powerdown | socat - UNIX-CONNECT:/tmp/monitor
          sleep 5
        fi
        ps -C qemu-system-x86_64
        WINDOWS7RUNNING=$?
        if [ $WINDOWS7RUNNING -eq 0 ]
        then
          echo Windows7 is still running. Waiting another 5 seconds
          sleep 5
        fi
        ps -C qemu-system-x86_64
        WINDOWS7RUNNING=$?
        if [ $WINDOWS7RUNNING -eq 0 ]
        then
          echo Windows7 is still running. Waiting another 5 seconds
          sleep 5
        fi
 ;;
esac

exit 0

