apiVersion: v1
kind: Pod
metadata:
  name: nginx-02
  namespace: ene
  labels:
    app: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
  tolerations:
    - key: spray
      value: red
      effect: NoSchedule
