# Dockerfile based on the latest debian 8 image
FROM debian:8
MAINTAINER eneuhauss@gmx.de

RUN apt-get update && \
  apt-get -y upgrade &&  \
  apt-get -y install \
    vim \
    git \
    puppet

ADD config/client/etc/puppet/puppet.conf /etc/puppet/puppet.conf

RUN /usr/bin/puppet agent --disable
