apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        configHash: ""
    spec:
      volumes:
      - name: secret-htpasswd-volume
        secret:
          secretName: nginx-protected
      - name: nginx-webcontent-volume
        configMap:
          name: nginx-webcontent
      - name: nginx-config-volume
        configMap:
          name: nginx-configmap-multi
      - name: webcontent-example
        emptyDir: {}
      containers:
      - image: registry.fritz.box/arm64v8/nginx
        name: nginx
        ports:
          - containerPort: 80
            name: http
        volumeMounts:
          - name: secret-htpasswd-volume
            mountPath: /etc/nginx/protected
          - name: nginx-config-volume
            mountPath: /etc/nginx
            readOnly: false
          - name: nginx-webcontent-volume
            mountPath: /usr/share/nginx/html
          - name: webcontent-example
            mountPath: /example.com
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 3
          periodSeconds: 60
      initContainers:
      - image: registry.fritz.box/arm64v8/nginx
        name: webcontent
        command: ['/bin/sh']
        args:
          - -c
          - >-
            echo "check this out!" > /example.com/index.html
        ports:
          - containerPort: 80
            name: http
        volumeMounts:
          - name: nginx-webcontent-volume
            mountPath: /usr/share/nginx/html
          - name: webcontent-example
            mountPath: /example.com
      - image: registry.fritz.box/arm64v8/nginx
        name: nginx-test
        command: ['nginx', '-t']
        ports:
          - containerPort: 80
            name: http
        volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx
            readOnly: false
          - name: webcontent-example
            mountPath: /example.com

