apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-confd-default-volume
        configMap:
          name: nginx-confd-default-dist
          #          name: nginx-confd-default
      containers:
      - image: registry.fritz.box/arm64v8/nginx
        name: nginx
        ports:
          - containerPort: 80
            name: http
        volumeMounts:
          - name: nginx-confd-default-volume
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
