apiVersion: v1
data:
  default.conf: |+
    # vim: set syntax=nginx:

    server {
        listen       80;
        root   /usr/share/nginx/html;
        }

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-confd-default
  namespace: nginx
