# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key   = false

  config.vm.define "web" do |web|
    web.vm.box 	    = "centos/7"
    web.vm.hostname = "web"
  end # config.vm.web

  config.vm.define "db" do |db|
    db.vm.box 	   = "centos/7"
    db.vm.hostname = "db"
  end # config.vm.web

  config.vm.network "private_network", type: "dhcp"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose       = "v"
    ansible.playbook      = "playbook.yml"
  end # config.vm.provision
end # Vagrant
