# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = [
    {
        :name => "master",
        :box  => "centos/7"
    },
    {
        :name => "slave1",
        :box  => "centos/7"
    },
    {
        :name => "slave2",
        :box  => "centos/7"
    },
]

Vagrant.configure("2") do |config|
  config.ssh.insert_key   = false
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder '.', '/vagrant', :disabled => true

#  config.vm.provision "ansible" do |ansible|
#    ansible.verbose       = "v"
#    ansible.playbook      = "playbook.yml"
#  end # config.vm.provision
# config each box
  boxes.each do |box|
    config.vm.define box[:name] do |config|
      config.vm.box  = box[:box]
      config.vm.hostname = box[:name]
    end # config.vm
  end # boxes
end # Vagrant
#
#  config.vm.define "web" do |web|
#    web.vm.box 	    = "centos/7"
#    web.vm.hostname = "web"
#  end # config.vm.web
#
#  config.vm.define "monitor" do |monitor|
#    monitor.vm.box      = "centos/7"
#    monitor.vm.hostname = "monitor"
#  end # config.vm.web
#
#  config.vm.define "logstash" do |logstash|
#    logstash.vm.box 	   = "centos/7"
#    logstash.vm.hostname   = "logstash"
#  end # config.vm.web
#
#  config.vm.define "elastic" do |elastic|
#    elastic.vm.box      = "centos/7"
#    elastic.vm.hostname = "elastic"
#  end # config.vm.web
#
#  config.vm.define "kibana" do |kibana|
#    kibana.vm.box      = "centos/7"
#    kibana.vm.hostname = "kibana"
#  end # config.vm.web
#
#  config.vm.define "bitbucket" do |bitbucket|
#    bitbucket.vm.box      = "debian/jessie64"
#    bitbucket.vm.hostname = "bitbucket"
#  end # config.vm.web
#
#  config.vm.define "confluence" do |confluence|
#    confluence.vm.box 	   = "debian/jessie64"
#    confluence.vm.hostname = "confluence"
#  end # config.vm.web
#
#  config.vm.define "jira" do |jira|
#    jira.vm.box      = "debian/jessie64"
#    jira.vm.hostname = "jira"
#  end # config.vm.web
#
