# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<EOF
yum install -y wget git vim
rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
rpm -ihv https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum install -y ansible
git clone https://github.com/erolneuhauss/studies.git
cp studies/ansible/ssh_config /home/vagrant/.ssh/
cp studies/ansible/insecure_private_key /home/vagrant/.ssh/id_rsa
cp studies/ansible/provision/vagrant_ansible_inventory /home/vagrant/
cp studies/ansible/provision/playbook.yml /home/vagrant/
chmod 0600 /home/vagrant/.ssh/id_rsa
chown vagrant:vagrant -R /home/vagrant
EOF

boxes = [
    {
        :name => "slave1",
        :box  => "centos/7"
    },
    {
        :name => "slave2",
        :box  => "centos/7"
    },
]

Vagrant.configure("2") do |config|
  config.ssh.insert_key   = false
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder '.', '/vagrant', :disabled => true

  config.vm.define "master" do |config|
    config.vm.box  = "centos/7"
    config.vm.hostname = "master"
    config.vm.provision "shell", inline: $script
  end # config.vm

#  config.vm.provision "ansible" do |ansible|
#    ansible.verbose       = "v"
#    ansible.playbook      = "playbook.yml"
#  end # config.vm.provision
# config each box
  boxes.each do |box|
    config.vm.define box[:name] do |config|
      config.vm.box  = box[:box]
      config.vm.hostname = box[:name]
    end # config.vm
  end # boxes
end # Vagrant
