---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: photo-filter
  namespace: s3photoapp
spec:
  ports:
  - port: 3002
    protocol: TCP
    targetPort: 3002
  selector:
    app: photo-filter
