---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: web-client
  namespace: s3photoapp
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: web-client
