---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: photo-storage
  namespace: s3photoapp
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: photo-storage
