filetype off
set cursorline
set encoding=utf8
set expandtab
set hlsearch
set incsearch
set number
set shiftwidth=2
set showcmd
set softtabstop=2
set tabstop=2
execute pathogen#infect()
execute pathogen#helptags()
filetype plugin indent on
syntax on
let g:airline_theme='powerlineish'
let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled = 1
set ruler
set laststatus=2
set showtabline=2
set background=light
set t_Co=256
set term=xterm-256color
colorscheme solarized
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
