#!~/.local/bin/ansible-playbook
---
- name: deploy kubernetes wordpress php7.3-fpm
  hosts: localhost
  connection: local
  serial: 1
  gather_facts: false
  become: false
  collections:
    - community.kubernetes
  tasks:
    - name: Create wordpress namespace
      k8s:
        name: wordpress
        api_version: v1
        kind: Namespace
        state: present

    - name: Create mysql-secrets from file
      k8s:
        state: present
        src: mysql-secrets.yml

    - name: Create mysql db deployment from file mysql.yaml
      k8s:
        state: present
        src: mysql.yaml

    - name: Create PersistentVolumeClaim for wordpress
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: wp-cephfs-pvc
            namespace: wordpress
            labels:
              app: wordpress
          spec:
            storageClassName: rook-cephfs
            accessModes:
            - ReadWriteMany
            resources:
              requests:
                storage: 1Gi

    - name: Create wordpress-secrets from file
      k8s:
        state: present
        src: wordpress-secrets.yml

    - name: delete nginx configmap
      k8s:
        state: absent
        api_version: v1
        kind: ConfigMap
        namespace: wordpress
        name: nginx-configmap

    - name: create nginx configmap from directory
      shell: kubectl --namespace=wordpress create configmap nginx-configmap --from-file=etc-nginx

    - name: delete php-fpm configmap
      k8s:
        state: absent
        api_version: v1
        kind: ConfigMap
        namespace: wordpress
        name: php-fpm-configmap

    - name: create nginx configmap from directory
      shell: kubectl --namespace=wordpress create configmap php-fpm-configmap --from-file=conf.d

      # if we have used cehpfs instead of ceph-rbd, we could have gone with two separate pods
      # one for wordpress-php7.3-fpm and one for nginx
      # with ceph-rbd, we only can mount the same volume only once in a pod
      # so with ceph-rbd, nginx container runs as a sidecar container
    - name: Create Deployment wordpress-php7.3-fpm
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: wordpress-php7.3-fpm
            namespace: wordpress
            labels:
              app: wordpress
          spec:
            selector:
              matchLabels:
                app: wordpress
            strategy:
              type: Recreate
            template:
              metadata:
                labels:
                  app: wordpress
              spec:
                affinity:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                      - matchExpressions:
                        - key: kubernetes.io/arch
                          operator: In
                          values:
                          - arm64
                volumes:
                - name: nginx-config-volume
                  configMap:
                    name: nginx-configmap
                - name: php-fpm-fastcgi-cache
                  emptyDir: {}
                - name: php-fpm-config-volume
                  configMap:
                    name: php-fpm-configmap
                - name: wordpress-persistent-storage
                  persistentVolumeClaim:
                    claimName: wp-cephfs-pvc
                initContainers:
                - image: registry.fritz.box/arm64v8/nginx
                  name: nginx-test
                  command: ['nginx', '-t']
                  ports:
                    - containerPort: 80
                      name: http
                  volumeMounts:
                  - name: php-fpm-fastcgi-cache
                    mountPath: /var/cache/nginx/wordpress
                    readOnly: false
                  - name: nginx-config-volume
                    mountPath: /etc/nginx
                    readOnly: false
                  - name: wordpress-persistent-storage
                    mountPath: /var/www/html
                containers:
                - image: registry.fritz.box/arm64v8/wordpress-php7.3-fpm
                  name: wordpress
                  envFrom:
                  - secretRef:
                      name: wordpress-secrets
                  ports:
                  - containerPort: 9000
                    name: https
                  volumeMounts:
                  - name: wordpress-persistent-storage
                    mountPath: /var/www/html
                  - name: php-fpm-config-volume
                    mountPath: /usr/local/etc/php/conf.d
                - image: registry.fritz.box/arm64v8/nginx
                  name: nginx
                  ports:
                    - containerPort: 80
                      name: http
                  volumeMounts:
                  - name: php-fpm-fastcgi-cache
                    mountPath: /var/cache/nginx/fastcgi_wordpress
                    readOnly: false
                  - name: nginx-config-volume
                    mountPath: /etc/nginx
                    readOnly: false
                  - name: wordpress-persistent-storage
                    mountPath: /var/www/html
                  livenessProbe:
                    httpGet:
                      path: /
                      port: http
                      scheme: HTTP
                      httpHeaders:
                        - name: Host
                          value: wordpress.example.com
                    initialDelaySeconds: 3
                    periodSeconds: 60

    - name: rollout restart wordpress
      shell: kubectl --namespace=wordpress rollout restart deployment wordpress-php7.3-fpm

    - name: Create Service for wordpress on port 9000
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: wordpress
            namespace: wordpress
            labels:
              app: wordpress
          spec:
            selector:
              app: wordpress
            ports:
            - protocol: TCP
              targetPort: 9000
              name: https
              port: 9000
            - protocol: TCP
              targetPort: 80
              name: http
              port: 80
