#!/usr/bin/env bash
MYUSER='automation'
MYCMD='ansible webservers,dbservers -b -m'

${MYCMD} user -a \
  "name=${MYUSER} \
  state=present"

${MYCMD} file -a \
  "path=~${MYUSER}/.ssh \
  state=directory \
  owner=${MYUSER} \
  group=${MYUSER} \
  mode=0700"

${MYCMD} copy -a \
  "src=~/.vagrant.d/insecure_private_key \
  dest=~${MYUSER}/.ssh/id_rsa \
  owner=${MYUSER} \
  group=${MYUSER} \
  mode=0644"

${MYCMD} authorized_key -a \
  "user=${MYUSER} \
  key=\"{{ lookup('file', './files/control_rsa.pub') }}\" \
  state=present \
  path=~${MYUSER}/.ssh/id_rsa.pub"

${MYCMD} lineinfile -a \
  "path=/etc/sudoers.d/${MYUSER} \
  line=\"${MYUSER} ALL=(ALL) NOPASSWD: ALL\" \
  create=true \
  validate='/usr/sbin/visudo -cf %s'"
