---
- hosts: database
  gather_facts: false
  become: true
  tasks:
    - template:
        src: server_list.j2
        dest: /etc/server_list_txt
        owner: automation
        mode: 0600
        setype: net_conf_t

