---
- hosts: all
  gather_facts: true
  become: true
  tasks:
    - sysctl:
        name: vm.swappiness
        value: 10
        reload: true
        sysctl_set: true
        state: enabled
      when: "'ansible_memory_mb' | int > 2048"

    - debug:
        msg: "Server memory less than 2048MB"
      when: "'ansible_memory_mb' | int < 2048"
