---
- hosts: webservers,database
  become: true
  gather_facts: false
  vars_files:
    - secret.yml
    - user_list.yml
  tasks:
    - block:
        - user:
            name: '{{ item.username }}'
            uid: '{{ item.uid }}'
            groups: wheel
            shell: /bin/bash
            password: "{{ user_password | string | password_hash('sha512') }}"
            state: present
            update_password: on_create
          loop: "{{ users }}"

        - authorized_key:
            user: "{{ item.username }}"
            key: "{{ lookup('file', './files/control_rsa.pub') }}"
            state: present
          loop: "{{ users }}"

        - copy:
            src: secrets/id_rsa
            dest: "/home/{{ item.username }}/.ssh/id_rsa"
            owner: '{{ item.username }}'
            group: '{{ item.username }}'
            mode: 0600
          loop: "{{ users }}"
      when: (inventory_hostname in groups['webservers'] and (item.uid | string)[0] == '1') or (inventory_hostname in groups['database'] and (item.uid | string)[0] == '2')
