---
- hosts: node3.example.local
  become: true
  gather_facts: false
  tasks:
    - yum:
        name:
          - httpd
          - firewalld
        state: present

    - service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - httpd
        - firewalld

    - group:
        name: wordpress
        state: present

    - name: cleanup
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/www/html/webcontent
        - /webcontent

    - sefcontext:
        target: '/webcontent(/.*)?'
        setype: httpd_sys_content_t
        state: present

    - command: restorecon -irv /webcontent

    - file:
        path: /webcontent
        owner: root
        group: wordpress
        mode: u=rwx,g=rwx,o=rx,g+s # or 02775
        setype: httpd_sys_content_t
        state: directory

    - file:
        src: /webcontent
        dest: /var/www/html/webcontent
        state: link

    - template:
        dest: /webcontent/index.html
        src: index.html.j2

    - get_url:
        url: "http://{{ inventory_hostname }}/webcontent/index.html"
        dest: /tmp

    - firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
